image: registry.gitlab.com/everythingfunctional/dockerfpm

variables:
    GIT_SUBMODULE_STRATEGY: normal

test:
  script:
    - fpm test unit_test
    - valgrind --leak-check=full --error-exitcode=1 build/gfortran_debug/test/unit_test/unit_test
    - ./run_io_tests.sh
