image: registry.gitlab.com/everythingfunctional/dockerfpm

variables:
    GIT_SUBMODULE_STRATEGY: normal

test:
  script:
    - fpm test --target unit_test
    - fpm test --target round_trip
    - ./run_io_tests.sh
