name = "iso_varying_string"
version = "1.0.0"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "2020 Brad Richardson"

[dev-dependencies]
vegetables = { git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v5.0.0" }
